# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 0c72dca5d41b1ed79e8d975bbe493b1f10a93317fa46e1d189f7d219450eeefa8da0d29259f67ecd5a25e6e73dfa01edfc8f837c8bbf2ea92b9cd64203e4a150

test:
  domain_name: example.com 
  secret_key_base: e667f5b33581b883289bb9c893389f9cb3873db0d96ab73e26de896767a201e21a1ed7e38ad40402355bc939aba7c810ac26ecc77522db97681bb5e045ca0a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
